mappings:
  DMSDocumentSet: SilverStripe\DMS\Model\DMSDocumentSet
  DMSDocument_versions: SilverStripe\DMS\Model\DMSDocument_versions
  DMSDocument: SilverStripe\DMS\Model\DMSDocument
  DMSJsonField: SilverStripe\DMS\Forms\DMSJsonField
  DMSGridFieldAddNewButton: SilverStripe\DMS\Admin\DMSGridFieldAddNewButton
  DMSDocumentAddController: SilverStripe\DMS\Admin\DMSDocumentAddController
  DMSDocumentAdmin: SilverStripe\DMS\Admin\DMSDocumentAdmin
  DMSUploadField: SilverStripe\DMS\Admin\DMSUploadField
  DMSUploadField_ItemHandler: SilverStripe\DMS\Admin\DMSUploadField_ItemHandler
  DMSGridFieldEditButton: SilverStripe\DMS\Admin\DMSGridFieldEditButton
  DocumentHtmlEditorFieldToolbar: SilverStripe\DMS\Admin\DocumentHtmlEditorFieldToolbar
  DMSGridFieldDetailForm_ItemRequest: SilverStripe\DMS\Admin\DMSGridFieldDetailForm_ItemRequest
  DMSDocumentAddExistingField: SilverStripe\DMS\Admin\DMSDocumentAddExistingField
  DMSDocumentInterface: SilverStripe\DMS\Interfaces\DMSDocumentInterface
  DMSInterface: SilverStripe\DMS\Interfaces\DMSInterface
  DMSDocumentTaxonomyExtension: SilverStripe\DMS\Extensions\DMSDocumentTaxonomyExtension
  DMSSiteTreeExtension: SilverStripe\DMS\Extensions\DMSSiteTreeExtension
  DMSTaxonomyTypeExtension: SilverStripe\DMS\Extensions\DMSTaxonomyTypeExtension
  MigrateToDocumentSetsTask: SilverStripe\DMS\Tasks\MigrateToDocumentSetsTask
  DMS: SilverStripe\DMS\DMS
  FileNotFoundException: SilverStripe\DMS\Exceptions\FileNotFoundException
  DMSDocument_Controller: SilverStripe\DMS\Control\DMSDocumentController
  DMSShortcodeHandler: SilverStripe\DMS\Tools\DMSShortcodeHandler
  ShortCodeRelationFinder: SilverStripe\DMS\Tools\ShortCodeRelationFinder
  DMSVersioningTest: SilverStripe\DMS\Tests\Model\DMSVersioningTest
  DMSDocumentSetTest: SilverStripe\DMS\Tests\Model\DMSDocumentSetTest
  DMSEmbargoTest: SilverStripe\DMS\Tests\Model\DMSEmbargoTest
  DMSDocumentTest: SilverStripe\DMS\Tests\Model\DMSDocumentTest
  StubRelatedDocumentExtension: SilverStripe\DMS\Tests\Stub\StubRelatedDocumentExtension
  DMSShortcodeHandlerTest: SilverStripe\DMS\Tests\ShortCode\DMSShortcodeHandlerTest
  ShortCodeRelationFinderTest: SilverStripe\DMS\Tests\ShortCode\ShortCodeRelationFinderTest
  DMSJsonFieldTest: SilverStripe\DMS\Tests\forms\DMSJsonFieldTest
  MigrateToDocumentSetsTaskTest: SilverStripe\DMS\Tests\Tasks\MigrateToDocumentSetsTaskTest
  DMSDocumentAddControllerTest: SilverStripe\DMS\Tests\Admin\DMSDocumentAddControllerTest
  DMSGridFieldAddNewButtonTest: SilverStripe\DMS\Tests\Admin\DMSGridFieldAddNewButtonTest
  DMSUploadField_ItemHandlerTest: SilverStripe\DMS\Tests\Admin\DMSUploadField_ItemHandlerTest
  DMSDocumentAdminTest: SilverStripe\DMS\Tests\Admin\DMSDocumentAdminTest
  DMSDocumentAddExistingFieldTest: SilverStripe\DMS\Tests\Admin\DMSDocumentAddExistingFieldTest
  DMSUploadFieldTest: SilverStripe\DMS\Tests\Admin\DMSUploadFieldTest
  DMSTest: SilverStripe\DMS\Tests\DMSTest
  DMSTaxonomyTypeExtensionTest: SilverStripe\DMS\Tests\Extensions\DMSTaxonomyTypeExtensionTest
  DMSSiteTreeExtensionTest: SilverStripe\DMS\Tests\Extensions\DMSSiteTreeExtensionTest
  DMSDocumentTaxonomyExtensionTest: SilverStripe\DMS\Tests\Extensions\DMSDocumentTaxonomyExtensionTest
  DMSFilesystemTestHelper: SilverStripe\DMS\Tests\DMSFilesystemTestHelper
  DMSDocumentControllerTest: SilverStripe\DMS\Tests\Control\DMSDocumentControllerTest
