---
Name: dmsconfig
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripe\DMS\Extensions\DMSSiteTreeExtension
  documents_enabled: true
HtmlEditorField_Toolbar:
  extensions:
    - SilverStripe\DMS\Admin\DocumentHtmlEditorFieldToolbar
SilverStripe\Core\Injector\Injector: {  }
